### ISSUE TITLE
Unexpected behavior of `future.seed = NULL`

### ISSUE THREAD

**Issue by odelmarcelle** [HenrikBengtsson/future.apply#100]
**Describe the bug**
Using `future.seed = NULL` does not issue a warning but behaves as `future.seed = FALSE`

**Reproduce example**
``` r
library(future.apply)
plan(sequential)
set.seed(0xBEEF)
saved_seed <- .Random.seed
y1 <- future_lapply(1:5, FUN = rnorm, future.seed = NULL)
y2 <- future_lapply(1:5, FUN = rnorm, future.seed = NULL)
all.equal(y1, y2)
#> [1] TRUE
all.equal(saved_seed, .Random.seed)
#> [1] TRUE

plan(multisession)
set.seed(0xBEEF)
y1 <- future_lapply(1:5, FUN = rnorm, future.seed = NULL)
y2 <- future_lapply(1:5, FUN = rnorm, future.seed = NULL)
all.equal(y1, y2)
#> [1] "Component 1: Mean relative difference: 0.6660136"
#> [2] "Component 2: Mean relative difference: 2.878881" 
#> [3] "Component 3: Mean relative difference: 0.458055" 
#> [4] "Component 4: Mean relative difference: 1.958599" 
#> [5] "Component 5: Mean relative difference: 1.851948"
all.equal(saved_seed, .Random.seed)
#> [1] TRUE
```

**Expected behavior**
Either `future.seed = NULL` should issue a warning when there is random number generation, and documentation should be updated in that way, or `future.seed = NULL` should behave as  `future.seed = NA` and effectively forward one step the RNG state.

**Session information**
``` r
sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19043)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=French_Belgium.1252  LC_CTYPE=French_Belgium.1252   
#> [3] LC_MONETARY=French_Belgium.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=French_Belgium.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.37        magrittr_2.0.2    R.cache_0.15.0   
#>  [5] rlang_1.0.1       fastmap_1.1.0     fansi_1.0.2       stringr_1.4.0    
#>  [9] styler_1.6.2      highr_0.9         tools_4.1.2       xfun_0.29        
#> [13] R.oo_1.24.0       utf8_1.2.2        cli_3.2.0         withr_2.4.3      
#> [17] htmltools_0.5.2   ellipsis_0.3.2    yaml_2.3.5        digest_0.6.29    
#> [21] tibble_3.1.6      lifecycle_1.0.1   crayon_1.5.0      purrr_0.3.4      
#> [25] R.utils_2.11.0    vctrs_0.3.8       fs_1.5.2          glue_1.6.1       
#> [29] evaluate_0.15     rmarkdown_2.11    reprex_2.0.1      stringi_1.7.6    
#> [33] compiler_4.1.2    pillar_1.7.0      R.methodsS3_1.8.1 backports_1.4.1  
#> [37] pkgconfig_2.0.3
```

**Comment by odelmarcelle** [comment]
I reckon that this behavior is correctly documented in the help page of `future()`.  However, the documentation of `future_lapply()` is perhaps misleading, notably the sentence:
 
"In all cases but `future.seed = FALSE`, the RNG state of the calling R processes after this function returns is guaranteed to be "forwarded one step"... "

**Comment by HenrikBengtsson** [comment]
Thank you for spotting this. I've tried to clarify this in commit b0ebff96.

FWIW, there was also a mentioning of `future.seed = NA`, which I dropped.  It actually still works, also in `future()`, but please don't use it. I think this stems from the days trying to figure out exactly what RNG schema the future framework should support. I don't recall correctly, but I also think I went back and forth about using `NULL` or `NA` and whether `NA` should be reserved for other things coming later. I'll add it to my internal list to sort this out, e.g. deprecated and defunct `NA`, or possibly have it replace `NULL` later or. Either way, using `NULL` (or `NA`) should be rare; the developer should be able to decide on `TRUE` or `FALSE`.
