### ISSUE TITLE
Error setallcol(x): verbose must be TRUE or FALSE`

### ISSUE THREAD

**Issue by tle4336** [HenrikBengtsson/future.apply#103]
I am currently in need of using the `future.chunk.size` parameter in `future_mapply()` function with the goal of speeding up the execution time of a big optimizer function, where there are 3 vectorized arguments with a bunch of other arguments added within the `MoreArgs = ...` . However, I kept bumping into the error `setallcol(x): verbose must be TRUE or FALSE` when setting the parameter `future.chunk.size = 3` (the lengths of my 3 vectorized arguments are 52). Is this a bug? I used `future.apply` (version `1.9.0`) and `future` (version `1.25.0`).

Also, when I run my code, it seems to me that every time it hits the `library(future.apply)` row, it starts encountering a very long `buffering` time where it seems to plan/compute everything before pushing out outputs at a breakneck speed. Is this a normal behavior? The buffering time takes way too long though.

**Comment by HenrikBengtsson** [comment]
Hi. Yes, a known problem with the latest **future** 1.25.0, that will be fixed in the next release. Please see https://github.com/HenrikBengtsson/future/discussions/621#discussioncomment-2715653 for details and how to workarounds for now.

**Comment by HenrikBengtsson** [comment]
> Also, when I run my code, it seems to me that every time it hits the library(future.apply) row, it starts encountering a very long buffering time where it seems to plan/compute everything before pushing out outputs at a breakneck speed. Is this a normal behavior? The buffering time takes way too long though.

```sh
>system.time(library(future.apply))
Loading required package: future
   user  system elapsed 
  0.681   0.024   0.705 
```

If that's what you see, it's probably something with your setup. Please post to https://github.com/HenrikBengtsson/future/discussions/, since I doubt it's a bug in the future framework.
