### ISSUE TITLE
Clear up global options usage with nested plans

### ISSUE THREAD

**Issue by maxim-h** [HenrikBengtsson/future.apply#116]
Hi. And thank you for a great package!

`future.globals.maxSize` option limits the amount of RAM that can be moved between processes. Very useful feature.

But obviously sometimes you need to increase it like so:

```r
options(future.globals.maxSize = [bigger number])
```

This breaks once you define a nested plan. For example

```r
plan(list(tweak(multisession, workers = 4), tweak(multisession, workers = 8)))
options(future.globals.maxSize = [bigger number])
```

The `future.globals.maxSize` seems to only apply to the outer plan, but not the inner one. This was reported [here](https://github.com/HenrikBengtsson/future/issues/185#issuecomment-1315276678). I couldn't find anything in the documentation on how to deal with such situation. 

The only work around I could find is to define the option twice: once globally, and once inside the outer function that is being ran. Like this, for example:

```r
plan(list(tweak(multisession, workers = 4), tweak(multisession, workers = 8)))
options(future.globals.maxSize = [bigger number])

future_lapply(
  outer_arg_list, 
  function(x) {
    options(future.globals.maxSize=[bigger number])
    
    future_lapply(
      inner_arg_list,
      function(y) {
        ...
      }
  }
  )
```

This seems inconvenient and error prone.
Is there a better method of defining these options for nested futures?
If not, perhaps there should be.

**Comment by HenrikBengtsson** [comment]
FYI, future.apply 1.11.1, fixing this, is now on CRAN.

**Comment by maxim-h** [comment]
Thank you!
Checked the new CRAN version. All works as expected.
