### ISSUE TITLE
Bug in documentation for future.globals?

### ISSUE THREAD

**Issue by snowpong** [HenrikBengtsson/future.apply#119]
https://github.com/HenrikBengtsson/future.apply/blob/52ebedb61369ef63555db00e930c33d8826dd43c/R/future_lapply.R#L70

Two bugs here I believe:

1. I don't think NULL is supported for future.globals, I think you mean FALSE instead of NULL? (at least it didn't work for me)
2. For future_lapply the default for future.globals is TRUE, while here it seems to imply "not" is the default?

**Comment by HenrikBengtsson** [comment]
Thanks for spotting this. Yes, `NULL` is not supported;

```r
> y <- future_lapply(1:2, FUN = identity, future.globals = NULL)
Error in getGlobalsAndPackagesXApply(FUN = FUN, args = args, MoreArgs = MoreArgs,  : 
  Invalid argument 'future.globals': NULL
```

It's probably in the docs, because it was supported way back in the days.

Fixed in the develop branch.

**Comment by snowpong** [comment]
Great, thanks!
