### ISSUE TITLE
odbcConnect is not loaded in globals

### ISSUE THREAD

**Issue by Rloveeee** [HenrikBengtsson/future.apply#19]
Hi All,

***
> library("future.apply")
>     library("RODBC")
>     plan(multiprocess, workers = 5)
>     fopts <- options()
>     print(exists("odbcConnect"))
***
[1] TRUE
***
>     FUN=function(x) { odbcConnect  }
>     xx=future.apply::future_lapply(FUN=FUN,X=c("EMA","EBM","ECO","O","LRC"),future.globals=ls())
***

Error in ...future.FUN(...future.X_jj, ...) : 
  objet 'odbcConnect' introuvable
****

It could the same underlying issues than the problem function.type problem.

Best

**Comment by HenrikBengtsson** [comment]
Using `future.globals=ls()` overrides whatever the automatic identification globals would do. Look at `ls()` to see what globals your telling it to use.

**Comment by HenrikBengtsson** [comment]
I'm closing since I believe I answered you question.  Feel free to reopen.
