### ISSUE TITLE
Add arguments future.stdout (and future.stderr)

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/future.apply#26]
Add arguments `future.stdout` (and `future.stderr`) to control ditto per future.

**Comment by HenrikBengtsson** [comment]
Added `future.stdout = TRUE` in the develop version.

**Comment by nick-youngblut** [comment]
So there's currently no option fo `future.stderr`? I love using batchtools and future.batchtools, but troubleshooting can be a pain. It would be great if the user had access to a data.frame that contained the jobs ran (eg., via `future_lapply`), job resources used, job exit codes, paths to stdout and stderr files, etc.

**Comment by HenrikBengtsson** [comment]
> So there's currently no option fo `future.stderr`?

There are a few ways to answer this, but it goes something like this:

1. The [**future**](https://cran.r-project.org/web/packages/future/) package does not provide an `stderr` argument, that is, it does _not_ provide means to capture output to standard error.

2. The reason why **future** does not capture standard error is that it _cannot_ be done reliably in R.  The reason for this is explained in https://github.com/HenrikBengtsson/Wishlist-for-R/issues/55.  Also, the R help more or less advice against doing it.

Note that message and warning conditions produced by `message()` and `warnings()` are captured and relayed.  They often end up being rendered on stderr when they bubble up to the top, but they don't have to - so if you're after those, they're already taken take of.


>  I love using batchtools and future.batchtools, but troubleshooting can be a pain. It would be great if the user had access to a data.frame that contained the jobs ran (eg., via future_lapply), job resources used, job exit codes, paths to stdout and stderr files, etc.

Not sure if this is related to capturing stderr or not, to **future.apply**, or to **(future.)batchtools** and it's a comment that cast a really wide net so hard to comment on.   Since this is posted to the **future.apply** issue tracker, I'll start by saying: As a developer, and as an end-user, you should interactive with `future_lapply()` exactly the same way regardless of future backend used.  Your code should not be written assuming that you're running only on a scheduler.  With that in mind, what does "access to a data.frame that contained the jobs ran" mean and how should that work?  Exactly how would you ask for that information even if it was collected?  I don't know the answer to this design question.

**Comment by nick-youngblut** [comment]
> With that in mind, what does "access to a data.frame that contained the jobs ran" mean and how should that work? Exactly how would you ask for that information even if it was collected? I don't know the answer to this design question?

How about creating a global variable (eg., `FUTURE_JOB_SUMMARY`) via the `assign()` function? It's not the prettiest solution, but maybe it's the best for the circumstances. 

In regards to the data collection, that would be specific to the scheduler, but that basic info should be obtainable for each job ID. I currently do that now for all snakemake runs on a SGE cluster, and I wish I had the same for future.apply. Even if I could get the jobIDs from the `future_*apply` functions would be enough to parse the requisite data from the qacct accounting table (eg., exit codes & job run times).

**Comment by HenrikBengtsson** [comment]
> How about creating a global variable (eg., `FUTURE_JOB_SUMMARY`) via the `assign()` function? It's not the prettiest solution, but maybe it's the best for the circumstances.

Nah, unfortunately, that won't do it.  First of all, that's explicitly against the CRAN Policy (https://cran.r-project.org/web/packages/policies.html).  Regardless, writing to the global environment is always a bad idea - it works as a temporary hack and for debugging and troubleshooting, but in the long run it'll just come back and bite you and end-users in one way or the other.  It will also not work when you do nested parallelization.

> ... if I could get the jobIDs from the future_*apply functions would be enough to parse the requisite data from the qacct accounting table (eg., exit codes & job run times).

Are you aware that future _labels_ make their way into the job names when you use future.batchtools / batchtools and have something like:

```sh
#$ -N <%= if (exists("job.name", mode = "character")) job.name else job.hash %>
```
in your batchtools template file (e.g. `~/.batchtools.sge.tmpl`).

Here's an example with plain futures,
```r
> library(future.batchtools)
> plan(batchtools_sge)
> f <- future(42, label = "hey")
```
This will show up in the scheduler as:
```sh
$ qstat
job-ID  prior   name    user    state submit/start at     queue    slots ja-task-ID 
-------------------------------------------------------------------------------------
1820803 0.00000 hey     alice   qw    05/28/2020 18:36:22             1        
```

With future.apply, you can use:
```r
> library(future.apply)
> library(future.batchtools)
> plan(batchtools_sge)
> y <- future_lapply(1:10, FUN = sqrt, future.label = "hey-%d")
```
This will show itself as:
```sh
$ qstat
job-ID  prior   name    user    state submit/start at     queue    slots ja-task-ID 
-------------------------------------------------------------------------------------
1820845 0.00000 hey-1   alice   qw    05/28/2020 18:40:27              1        
1820846 0.00000 hey-2   alice   qw    05/28/2020 18:40:29              1        
1820847 0.00000 hey-3   alice   qw    05/28/2020 18:40:31              1        
1820848 0.00000 hey-4   alice   qw    05/28/2020 18:40:33              1        
1820849 0.00000 hey-5   alice   qw    05/28/2020 18:40:34              1        
1820850 0.00000 hey-6   alice   qw    05/28/2020 18:40:36              1        
1820851 0.00000 hey-7   alice   qw    05/28/2020 18:40:38              1        
1820852 0.00000 hey-8   alice   qw    05/28/2020 18:40:40              1        
1820853 0.00000 hey-9   alice   qw    05/28/2020 18:40:42              1        
1820854 0.00000 hey-10  alice   qw    05/28/2020 18:40:44              1        
```

This should allow you to map futures in future.apply calls to job names.  If you don't specify them, the default is `future.label = "future_lapply-%d"`.

**Comment by nick-youngblut** [comment]
The `future.label` method is an interesting idea, but it could get complicated if the user uses those same labels for multiple runs (eg., rerunning `future*apply()` a 2nd time after the 1st time failed). The user would have to parse the jobs info not only by the `hey-` label, but also by the time of execution, which could get messy. Alternatively, the user would have to be very careful about using a new label each time the future.apply function was called.

What about just serializing the data.frame to a file in a temporary directory? Another function could be used for check for that file and read in the data.frame. The challenge would be to make sure that the file is specific to each particular `future*apply()` call, but this could be done via `plan()`, right?

**Comment by HenrikBengtsson** [comment]
> ... Alternatively, the user would have to be very careful about using a new label each time the future.apply function was called.

That's what I had in mind, e.g. using a unique ID per session.  It's still not clear what your use case is - to me it sounds like you're after this for troubleshooting purposes.

> What about just serializing the data.frame to a file in a temporary directory? 

I say that such an API has the same problems as one that writes to user's global environment.

Having said this, ...

> Another function could be used for check for that file and read in the data.frame. The challenge would be to make sure that the file is specific to each particular future*apply() call, but this could be done via plan(), right?

Internally, future.batchtools write the batchtools registries to unique subfolders under `./.future/`.  The location can be controlled by option `future.cache.path` or environment variable `R_FUTURE_CACHE_PATH`.  The content of these subfolders are all batchtools specific, but they do contain additional breadcrumbs that are not parsed/read into the future framework.  These folders are automatically deleted when futures are resolved but this can be disabled by setting `options(future.delete = FALSE)` - this is currently an internal R option.

The point of the latter is to give you something to work with.  How to gather the benchmarking/profiling information you're looking for is a whole different challenge.  You could investigate what's available from batchtools.  Many schedulers do a decent job on gather the basics - also in a live fashion.   In the long term, the future framework might be able to gather some stats (https://github.com/HenrikBengtsson/future/issues/59) but that requires lots of research in order to get right .

**Comment by nick-youngblut** [comment]
My use case is just using future.apply on an SGE cluster effectively. Most often, I have to guess for the amount of resources required (eg., job time & memory) and if I get it wrong or my job dies for another reason, it's hard to troubleshoot the error in a smart way (vs just trying with more resources), given the complex (yet incomplete) output written by future.apply functions in the case of an error. The user doesn't see directly which of the jobs dies, how long each job ran for, the exit codes, etc. One can investigate the cache folders, but only if they set the option to not delete them and then know what they are looking for in the folders. 
It's often pretty frustrating for me, and for almost all members of my research group, they have given up on it due to the complexities of troubleshooting failed jobs. They see a complex error message written to the screen with no clear indication of what happened, and then they give up on running the jobs on the cluster. So instead, most just use (and abuse) our communal server (local multicore jobs) instead of using the cluster. If it's too complicated/frustrating, users won't actually use it.

**Comment by nick-youngblut** [comment]
Is there a way to get the cashe directory location in the batchtools template file? If so, I'm considering creating a script that runs after `Rscript -e 'batchtools::doJobCollection("<%= uri %>")'` to summarize the job info for each job (eg., resources used & exit codes).

**Comment by HenrikBengtsson** [comment]
Only got a few minutes, so won't comment on the R/future level ask on this (because I don't have an answer and haven't thought about it).  However, I can comment on:

> creating a script that runs after Rscript -e 'batchtools::doJobCollection("<%= uri %>")' to summarize the job info for each job (eg., resources used & exit codes).

Not sure if you know, but with SGE you can add:

```sh
## End-of-job summary, if running as a job
[[ -n "$JOB_ID" ]] && qstat -j "$JOB_ID"
```

at the very end of your script.  This will dump lots of useful information from SGE to stdout before it exits.

**Comment by nick-youngblut** [comment]
Thanks! That's definitely helpful for getting info on the jobs the succeeded/failed. Just to check, is there any function that I can run post `future*apply()` to get the future cache directory?

**Comment by HenrikBengtsson** [comment]
No, I don't think so, because it's only available as an internal, private field of each Future object.  The code that creates the folder is `future.batchtools:::future_cache_path()`.  As you probably already know, the closest you can get is `Sys.getenv("R_FUTURE_CACHE_PATH", ".future"))` but you won't be able to identify the specific subfolder.

**Comment by HenrikBengtsson** [comment]
Forgot to say, you might wanna reach out to {batchtools} and ask if there's a way to find the registry path/filename when the batchtools template is processed.  That could be a way forward.

**Comment by nick-youngblut** [comment]
Thanks for the advice. I might just switch to `batchMap` + `getJobTable`

**Comment by nick-youngblut** [comment]
I've tried to alter the cache path to make a new one for each `future*apply` call: 

```
default.resources = list(h_rt = '00:59:00',
                         h_vmem = '4G',
                         threads = '1',
                         omp.threads = '1',
                         blas.threads = '1',
                         conda.env = 'py3',
                         conda.path = '/ebio/abt3_projects/software/miniconda3_gt4.4/bin')
cluster.functions = makeClusterFunctionsSGE(template = '~/.batchtools.tmpl')

# directories
temp.dir = file.path('/ebio/abt3_scratch/', Sys.info()[['user']], 'batchtools_tmp')
dir.create(temp.dir, showWarnings = FALSE, recursive = TRUE)
cache_dir = file.path('/ebio/abt3_scratch/', Sys.info()[['user']],
                      'batchtools_cache', uuid::UUIDgenerate())
dir.create(cache_dir, showWarnings = FALSE, recursive = TRUE)
Sys.setenv('R_FUTURE_CACHE_PATH' = cache_dir)
## setting
options(future.cache.path = cache_dir,
        future.wait.interval = 2.0)
```

This does create a new cache path each time and in the base directory that I want, which is nice, given that the default of `pwd/.future` was always a pain when using git. However, only the `sessioninfo.txt` file is written to the cache path, and `*.log` files are never written.
