### ISSUE TITLE
Add callbacks

### ISSUE THREAD

**Issue by dipterix** [HenrikBengtsson/future.apply#33]
Is there ways to add small callback functions for each iterations in `future_lapply`?

I would like `FUN` to be async but before each iteration, add a callback running in main process to indicating progress updates (such as shiny `progress$inc(...)`) or just print the iteration number. This would help users to keep track of the total progress (say an algorithm runs for 5 hours then error occurs, I'm able to know which iteration has problem)

```
f = list()
for(e in seq_along(X)){
    # Main thread, before main chunk
    callback(e)

    # Async code
    f[[e]] <- future({FUN(X[e], ...)})
}
return(values(f))

**Comment by HenrikBengtsson** [comment]
I understand that you're asking for callbacks but it sounds like you're really after progress bars, so, as I just mentioned in Issue #34 ...

The [progressr](https://github.com/HenrikBengtsson/progressr) package was created for the purpose of being able to get progress updates in any context, including when doing parallel processing.  It's makes no assumptions about the future framework, and vice verse.

Here's an example from its README:
```r
library(future.apply)
plan(multisession)

library(progressr)
handlers("progress", "beepr")

xs <- 1:5

with_progress({
  p <- progressor(along = xs)
  y <- future_lapply(xs, function(x, ...) {
    p(sprintf("x=%g", x))
    Sys.sleep(6.0-x)
    sqrt(x)
  })
})
```

**Comment by HenrikBengtsson** [comment]
If you don't like the progressr package, you can signal your own conditions and set up condition handlers for those.  Just make sure they inherit `immediateCondition`.  This approach can be used as an approximate proxy for calling handlers.

**Comment by dipterix** [comment]
Can proxy `immediateCondition` fire signals containing arbitrary R object? Like I fire an R expression and receive it in main session and execute it? That would be cool.

**Comment by HenrikBengtsson** [comment]
Conditions can contain any R object and it's the whole condition object that is signalled. See `?withCallingHandlers`. Conditions are cool.
