### ISSUE TITLE
is this package by-default run on multicore?

### ISSUE THREAD

**Issue by ravinder387** [HenrikBengtsson/future.apply#76]
plan(multisession)  i guess I don't need to write
**If i'll use this package for make my R package? is it run on multi-core by default**
but if user want to use in distributed way local network or in cloud.. it is user responsibility. kindly help me

**Comment by HenrikBengtsson** [comment]
The future framework uses 'sequential' processing by default, which means that **future.apply** also runs everything sequentially by default.  This can be seen by:

```r
> library(future.apply)
Loading required package: future
> plan()
sequential:
- args: function (..., envir = parent.frame())
- tweaked: FALSE
- call: NULL
```

To run in parallel, the user needs to declare that using the `plan()` function, e.g.

```r
plan(multisession)
```

Does this answer your question?

**Comment by ravinder387** [comment]
thank you sir..
