### ISSUE TITLE
Struggling to get cluster plan working

### ISSUE THREAD

**Issue by tyluRp** [HenrikBengtsson/future.apply#78]
I have 3 raspberry pi's that I can SSH into without providing a password. I run:
```r
library(future.apply)

workers <- c("rpi-main", "rpi-worker-01", "rpi-worker-02")
plan(cluster, workers = workers)
```

And I get:
```r
bash: /Library/Frameworks/R.framework/Resources/bin/Rscript: No such file or directory
```

Any ideas what I'm doing wrong? If I provide the IP instead of the hostname, it asks for password and uses `<username>@<ip>` where the username isn't what I actually want.

**Comment by HenrikBengtsson** [comment]
Try with:

```r
plan(cluster, workers=workers, homogeneous=FALSE)
```

**Comment by tyluRp** [comment]
So I just realized I don't have R installed on one of the Pi's, but I tried with a node that does with:
```r
library(future.apply)

workers <- c("rpi-worker-01")
plan(cluster, workers = workers, homogeneous=FALSE)
```

And I get:

```r
Error: Initialization of plan() failed, because the test future used for validation failed. The reason was: Package 'future' is not installed on worker (r_version: 4.0.3 (2020-10-10); platform: aarch64-unknown-linux-gnu (64-bit); os: Linux 5.8.0-1010-raspi #13-Ubuntu SMP PREEMPT Wed Dec 9 17:14:07 UTC 2020; hostname: worker-01)
```

**Comment by tyluRp** [comment]
Oh and now that I've actually read the error message... maybe I should install `future` :D

**Comment by HenrikBengtsson** [comment]
That's great to hear.  Could you please check that it also works with `homogeneous = NULL` for you, i.e.

```r
plan(cluster, workers = workers, homogeneous=NULL)
```

It should work.

I'm planning to make `homogeneous=NULL` the default in **future**, so that you don't have to specify it at all;

```r
plan(cluster, workers = workers)
```

**Comment by tyluRp** [comment]
With `homogeneous = NULL`, I get the same error about missing Rscript.

```r
library(future)

workers <- c("rpi-main", "rpi-worker-01", "rpi-worker-02")
plan(cluster, workers = workers, homogeneous=NULL)
#> bash: /Library/Frameworks/R.framework/Resources/bin/Rscript: No such file or directory
```

It basically just hangs there and I end up stopping the command.
