### ISSUE TITLE
immediateCondition not immediate for sequential?

### ISSUE THREAD

**Issue by rickhelmus** [HenrikBengtsson/future.apply#79]
Hello,

More of a question perhaps, and also not fully sure if it belongs to `future` or `future.apply`.

I am just toying with signalling conditions:

```R
future::plan("multisession")
withCallingHandlers({
    future.apply::future_lapply(seq_len(10), function(i)
    {
        signalCondition(structure(class = c("immediateCondition", "condition"),
                                  list(message = "hi", call = sys.call())))
        Sys.sleep(1)
    })
}, immediateCondition = function(cond) cat(sprintf("cond: %s\n", cond)))
```
This works nicely, however, when I change the plan to `sequential` all the conditions are queued until the loop is finished. Interestingly, `progressr`, works just fine with both plans, and I am pretty curious why :-)

**Comment by HenrikBengtsson** [comment]
Not at a computer right now, but I suspect it's because the future for an active sink of stdout that captures your `cat()` output. Try using `message()` instead.

**Comment by rickhelmus** [comment]
Ah yes, nice! `message` works fine indeed :-) Setting `future.stdout` to `NA` also works (although this is not recommended?).

Thanks,
Rick

**Comment by HenrikBengtsson** [comment]
Just a follow-up here in case someone finds this later:

Using:

```r
future::plan("sequential", split = TRUE)
```

avoids having to specify `future.stdout = NA`, because it "splits" the standard output so that it's both captured and outputted immediately.
